# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-BF2S
version:      0.03
version_from: lib/Net/BF2S.pm
installdirs:  site
requires:
    WWW::BF2S:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
